//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QnectMe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QnectMe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://192.168.1.200.
        /// </summary>
        public static string DefaultEndpoint {
            get {
                return ResourceManager.GetString("DefaultEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :8080.
        /// </summary>
        public static string DefaultPort {
            get {
                return ResourceManager.GetString("DefaultPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com.facebook.katana.
        /// </summary>
        public static string droidPackName_FB {
            get {
                return ResourceManager.GetString("droidPackName_FB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com.linkedin.android.
        /// </summary>
        public static string droidPackName_LI {
            get {
                return ResourceManager.GetString("droidPackName_LI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com.vkontakte.android.
        /// </summary>
        public static string droidPackName_VK {
            get {
                return ResourceManager.GetString("droidPackName_VK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.googleapis.com/oauth2/v4/token.
        /// </summary>
        public static string GoogleAccessTokenUrl {
            get {
                return ResourceManager.GetString("GoogleAccessTokenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Google&quot;.
        /// </summary>
        public static string GoogleAuthorization {
            get {
                return ResourceManager.GetString("GoogleAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://accounts.google.com/o/oauth2/auth.
        /// </summary>
        public static string GoogleAuthorizeUrl {
            get {
                return ResourceManager.GetString("GoogleAuthorizeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 808554759122-bia2qpvmrf52mrjop59g8ed0n3bidsv1.apps.googleusercontent.com.
        /// </summary>
        public static string GoogleClientId {
            get {
                return ResourceManager.GetString("GoogleClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 808554759122-us26der4dmtbgknp0ps481rccb74ar1m.apps.googleusercontent.com.
        /// </summary>
        public static string GoogleClientIdWeb {
            get {
                return ResourceManager.GetString("GoogleClientIdWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urn:ietf:wg:oauth:2.0:oob:auto.
        /// </summary>
        public static string GoogleRedirectUrl {
            get {
                return ResourceManager.GetString("GoogleRedirectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com.googleusercontent.apps.808554759122-bia2qpvmrf52mrjop59g8ed0n3bidsv1:/oauth2redirect.
        /// </summary>
        public static string GoogleRedirectUrl1 {
            get {
                return ResourceManager.GetString("GoogleRedirectUrl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.googleapis.com/auth/userinfo.email.
        /// </summary>
        public static string GoogleScope {
            get {
                return ResourceManager.GetString("GoogleScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/.
        /// </summary>
        public static string linkFB {
            get {
                return ResourceManager.GetString("linkFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.linkedin.com/in/.
        /// </summary>
        public static string linkLI {
            get {
                return ResourceManager.GetString("linkLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.vk.com/.
        /// </summary>
        public static string linkVK {
            get {
                return ResourceManager.GetString("linkVK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Microsoft&quot;.
        /// </summary>
        public static string MicrosoftAuthorization {
            get {
                return ResourceManager.GetString("MicrosoftAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://login.live.com/oauth20_token.srf.
        /// </summary>
        public static string MSAccessTokenUrl {
            get {
                return ResourceManager.GetString("MSAccessTokenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://apis.live.net/v5.0/me.
        /// </summary>
        public static string MSApiMe {
            get {
                return ResourceManager.GetString("MSApiMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://login.live.com/oauth20_authorize.srf.
        /// </summary>
        public static string MSAuthorizeUrl {
            get {
                return ResourceManager.GetString("MSAuthorizeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 021fc494-0317-4ef7-824c-c81c40fa98a5.
        /// </summary>
        public static string MSClientId {
            get {
                return ResourceManager.GetString("MSClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://login.microsoftonline.com/common/oauth2/nativeclient.
        /// </summary>
        public static string MSRedirectUrl {
            get {
                return ResourceManager.GetString("MSRedirectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://graph.microsoft.com/user.read.
        /// </summary>
        public static string MSScope {
            get {
                return ResourceManager.GetString("MSScope", resourceCulture);
            }
        }
    }
}
